"""
RateLimiter — sets up nftables (preferred) or iptables rules to:
  • rate-limit new SSH connections per source IP
  • protect against SYN floods (SYN cookies + limit)
  • maintain a kernel-level banned_ips set for O(log n) lookup
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from modules.core import ConfigManager, get_logger

_LOG = get_logger("protection.rate_limiter")


class RateLimiter:

    def __init__(self, cfg: ConfigManager) -> None:
        self._cfg = cfg
        c = cfg.section("rate_limiter")
        self._enabled: bool = c.get("enabled", True)
        self._backend: str = c.get("backend", "nftables")
        self._rate: int = c.get("new_connections_per_second", 3)
        self._burst: int = c.get("burst", 10)
        self._table: str = c.get("table_name", "ssh_fortress")
        self._chain: str = c.get("chain_name", "ssh_ratelimit")
        self._ssh_port: int = cfg.get("ssh", "port", default=22)
        self._syn_cookies: bool = c.get("syn_cookies", True)

    # ── public API ───────────────────────────────────────────────────────────

    def apply(self, dry_run: bool = False) -> bool:
        if not self._enabled:
            _LOG.info("Rate limiter disabled — skipping")
            return True

        if self._backend == "nftables":
            return self._apply_nftables(dry_run)
        return self._apply_iptables(dry_run)

    def flush(self) -> None:
        """Remove all SSH Fortress firewall rules (safe rollback)."""
        if self._backend == "nftables":
            self._run(["nft", "delete", "table", "inet", self._table])
        else:
            self._run(["iptables", "-F", "SSH_FORTRESS"])
            self._run(["iptables", "-X", "SSH_FORTRESS"])

    # ── nftables ─────────────────────────────────────────────────────────────

    def _apply_nftables(self, dry_run: bool) -> bool:
        ruleset = self._nftables_ruleset()
        if dry_run:
            _LOG.info("DRY RUN — nftables ruleset:")
            print(ruleset)
            return True
        # Write to a temp file, then atomic load
        tmp = Path("/tmp/ssh-fortress.nft")
        tmp.write_text(ruleset)
        ok = self._run(["nft", "-f", str(tmp)]) == 0
        tmp.unlink(missing_ok=True)
        if ok:
            self._persist_nftables_rules()
            if self._syn_cookies:
                self._enable_syn_cookies()
        _LOG.info("nftables rules applied" if ok else "nftables rules FAILED")
        return ok

    def _nftables_ruleset(self) -> str:
        port = self._ssh_port
        rate = self._rate
        burst = self._burst
        table = self._table
        return f"""#!/usr/sbin/nft -f
# SSH Fortress — nftables ruleset
# Generated by ssh-fortress

table inet {table} {{

    # Kernel-level banned IPs set (populated by BruteForceProtector)
    set banned_ips {{
        type ipv4_addr
        flags dynamic, timeout
        timeout 86400s
    }}

    set banned_ips6 {{
        type ipv6_addr
        flags dynamic, timeout
        timeout 86400s
    }}

    # Per-IP connection rate tracker
    set ssh_meter {{
        type ipv4_addr
        flags dynamic
    }}

    chain {self._chain} {{
        type filter hook input priority filter; policy accept;

        # Drop known banned IPs immediately (kernel hash lookup)
        ip saddr @banned_ips drop
        ip6 saddr @banned_ips6 drop

        # Established/related — pass without rate check
        ct state established,related accept

        # SYN flood guard
        tcp flags & (fin|syn|rst|psh|ack|urg) == syn \\
            limit rate over 100/second burst 200 packets drop

        # Rate limit new SSH connections
        tcp dport {port} ct state new \\
            limit rate over {rate}/second burst {burst} packets \\
            log prefix "SSH_FORTRESS_RATELIMIT: " drop

        # Log & count new SSH connections (pass)
        tcp dport {port} ct state new \\
            limit rate {rate}/second burst {burst} packets accept
    }}
}}
"""

    def _persist_nftables_rules(self) -> None:
        # RHEL/Fedora: nftables.conf; Debian/Ubuntu: /etc/nftables.conf
        for path in ("/etc/nftables.conf", "/etc/sysconfig/nftables.conf"):
            if Path(path).exists():
                self._run(["nft", "list", "ruleset"], stdout_file=path)
                return

    # ── iptables ─────────────────────────────────────────────────────────────

    def _apply_iptables(self, dry_run: bool) -> bool:
        rules = self._iptables_rules()
        if dry_run:
            _LOG.info("DRY RUN — iptables rules:")
            for r in rules:
                print(" ".join(r))
            return True
        for rule in rules:
            self._run(rule)
        if self._syn_cookies:
            self._enable_syn_cookies()
        _LOG.info("iptables rules applied")
        return True

    def _iptables_rules(self) -> list[list[str]]:
        port = str(self._ssh_port)
        rate = f"{self._rate}/second"
        burst = str(self._burst)
        return [
            ["iptables", "-N", "SSH_FORTRESS"],
            # Rate limit
            ["iptables", "-A", "INPUT", "-p", "tcp", "--dport", port,
             "-i", "eth0", "-m", "state", "--state", "NEW",
             "-m", "recent", "--set", "--name", "SSH"],
            ["iptables", "-A", "INPUT", "-p", "tcp", "--dport", port,
             "-i", "eth0", "-m", "state", "--state", "NEW",
             "-m", "recent", "--update", "--seconds", "60",
             "--hitcount", str(self._burst), "--name", "SSH",
             "-j", "DROP"],
            # SYN flood
            ["iptables", "-A", "INPUT", "-p", "tcp", "--syn",
             "-m", "limit", f"--limit", f"{self._rate}/s",
             f"--limit-burst", burst, "-j", "ACCEPT"],
            ["iptables", "-A", "INPUT", "-p", "tcp", "--syn", "-j", "DROP"],
        ]

    # ── helpers ──────────────────────────────────────────────────────────────

    def _enable_syn_cookies(self) -> None:
        try:
            Path("/proc/sys/net/ipv4/tcp_syncookies").write_text("1")
            _LOG.info("SYN cookies enabled")
        except Exception as e:
            _LOG.warning("Could not enable SYN cookies", error=str(e))

    def _run(self, cmd: list[str], stdout_file: str | None = None) -> int:
        try:
            kwargs: dict = {"capture_output": True, "timeout": 10}
            if stdout_file:
                kwargs = {"stdout": open(stdout_file, "w"), "stderr": subprocess.PIPE, "timeout": 10}
            result = subprocess.run(cmd, **kwargs)
            if result.returncode != 0:
                err = result.stderr.decode() if isinstance(result.stderr, bytes) else str(result.stderr)
                _LOG.warning("Command failed", cmd=" ".join(cmd), stderr=err.strip())
            return result.returncode
        except Exception as e:
            _LOG.error("Command error", cmd=" ".join(cmd), error=str(e))
            return 1
